# Generated by Django 5.2.15 on 2026-07-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_use_groups_for_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shipping_postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
