# Generated by Django 5.2.15 on 2026-07-10 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_recentlyviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='billing_same',
        ),
    ]
